from sqlalchemy import Column, Integer, String, DateTime, Text, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime
from models.user import Base

class History(Base):
    __tablename__ = "history"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    session_id = Column(String, unique=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    agent_name = Column(String, nullable=False)  # e.g., "Resume Analyzer", "Interview Simulator", etc.
    summary_text = Column(Text)  # e.g., "Score: 85", "Risk: YELLOW", "Generated Successfully"
    full_output = Column(Text)  # Complete JSON output/text generated by the agent
    action_type = Column(String)  # e.g., "analyze", "generate", "simulate"
    
    def to_dict(self):
        """Convert history record to dictionary for JSON serialization"""
        return {
            "id": self.id,
            "user_id": self.user_id,
            "session_id": self.session_id,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "agent_name": self.agent_name,
            "summary_text": self.summary_text,
            "full_output": self.full_output,
            "action_type": self.action_type
        }